language: ruby
sudo: false

rvm:
 - 2.2.3

cache: 
  bundler: true

env:
  - DB=pgsql

services:
  - postgresql

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database lodestar_test' -U postgres

script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rake

branches:
  only:
  - master
