production:
  title:     CIRTL Network
  sub-title: Center for Integration of Research, Teaching and Learning
development:
  title:     CIRTL Network
  sub-title: Center for Integration of Research, Teaching and Learning
